### PR TITLE
update to Unifont 9 (for Unicode 9 charwidths)

### PR DESCRIPTION
**Pull request by stevengj**
Since we bumped to Unicode 9 (in #70), we should also update to the latest version of GNU Unifont when computing character widths.

This is needed to tag a new release (#72).

### CODE REVIEW

**Comment by stevengj** [comment]
@jiahao, what's going on with AppVeyor?

**Comment by stevengj** [comment]
Okay, seems like AppVeyor problems were just a temporary glitch on their side; I saw the same failure on multiple projects.

**Comment by tkelman** [comment]
doesn't unicode 9 address the char width issue we needed this unifont stuff to address?

**Comment by Keno** [comment]
Most of it.

**Pull request merged**
