### PR TITLE
Fix Travis build and improve build reproducibility

### PR DESCRIPTION
**Pull request by petercolberg**
The first commit fixes the Travis builds, which are currently failing. I could also reproduce the updated data file on Debian unstable using Ruby 2.1.5p273. The subsequent commits make the process of generating the data file more robust, which is desirable for distribution packagers that wish to reproduce the entire build process.

### CODE REVIEW

**Comment by stevengj** [comment]
Sounds good, although I suspect that those of us on OSX will get a different data file.  (That was the problem we had in the past.  Both the data files are apparently valid, but the indexing of the tables is slightly different.)

**Comment by petercolberg** [comment]
I experimented with the MingW build by removing the fstab line, but now AppVeyor is hanging.

**Comment by petercolberg** [comment]
On Debian unstable with Ruby 2.1.5p273, the broken commit e52c8c4 produces a file that lacks the following entries in `utf8proc_properties` compared to the shipped `utf8proc_data.c`. What do these particular entries mean?
```
@@ -7971,7 +7971,6 @@
   {UTF8PROC_CATEGORY_LO, 0, UTF8PROC_BIDI_CLASS_R, 0, NULL, NULL, -1, -1, -1, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_OTHER, 2},
   {UTF8PROC_CATEGORY_LM, 0, UTF8PROC_BIDI_CLASS_R, 0, NULL, NULL, -1, -1, -1, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_OTHER, 2},
   {UTF8PROC_CATEGORY_PO, 0, UTF8PROC_BIDI_CLASS_R, 0, NULL, NULL, -1, -1, -1, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_OTHER, 2},
-  {UTF8PROC_CATEGORY_MN, 220, UTF8PROC_BIDI_CLASS_NSM, 0, NULL, NULL, -1, -1, -1, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_OTHER, 0},
   {UTF8PROC_CATEGORY_MC, 0, UTF8PROC_BIDI_CLASS_L, 0, NULL, NULL, -1, -1, -1, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_SPACINGMARK, 0},
   {UTF8PROC_CATEGORY_LO, 0, UTF8PROC_BIDI_CLASS_L, 0, NULL, NULL, -1, -1, -1, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_OTHER, 2},
   {UTF8PROC_CATEGORY_LO, 0, UTF8PROC_BIDI_CLASS_L, 0, NULL, NULL, -1, -1, -1, 7888, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_OTHER, 2},
@@ -8241,7 +8240,6 @@
   {UTF8PROC_CATEGORY_NO, 0, UTF8PROC_BIDI_CLASS_ON, 0, NULL, NULL, -1, -1, -1, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_OTHER, 1},
   {UTF8PROC_CATEGORY_PO, 0, UTF8PROC_BIDI_CLASS_ON, 0, NULL, NULL, -1, -1, -1, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_OTHER, 2},
   {UTF8PROC_CATEGORY_PD, 0, UTF8PROC_BIDI_CLASS_ON, 0, NULL, NULL, -1, -1, -1, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_OTHER, 2},
-  {UTF8PROC_CATEGORY_LO, 0, UTF8PROC_BIDI_CLASS_L, 0, NULL, NULL, -1, -1, -1, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_SPACINGMARK, 2},
   {UTF8PROC_CATEGORY_LO, 0, UTF8PROC_BIDI_CLASS_L, 0, NULL, NULL, -1, -1, -1, 9044, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_OTHER, 2},
   {UTF8PROC_CATEGORY_LO, 0, UTF8PROC_BIDI_CLASS_L, 0, utf8proc_sequences + 2397, NULL, -1, -1, -1, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_OTHER, 2},
   {UTF8PROC_CATEGORY_LO, 0, UTF8PROC_BIDI_CLASS_L, 0, NULL, NULL, -1, -1, -1, 9112, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_OTHER, 2},
@@ -10561,7 +10559,6 @@
   {UTF8PROC_CATEGORY_LL, 0, UTF8PROC_BIDI_CLASS_L, 0, NULL, NULL, 42650, -1, 42650, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_OTHER, 1},
   {UTF8PROC_CATEGORY_LM, 0, UTF8PROC_BIDI_CLASS_L, UTF8PROC_DECOMP_TYPE_SUPER, utf8proc_sequences + 1638, NULL, -1, -1, -1, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_OTHER, 1},
   {UTF8PROC_CATEGORY_LM, 0, UTF8PROC_BIDI_CLASS_L, UTF8PROC_DECOMP_TYPE_SUPER, utf8proc_sequences + 1642, NULL, -1, -1, -1, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_OTHER, 1},
-  {UTF8PROC_CATEGORY_MN, 230, UTF8PROC_BIDI_CLASS_NSM, 0, NULL, NULL, -1, -1, -1, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_OTHER, 0},
   {UTF8PROC_CATEGORY_LU, 0, UTF8PROC_BIDI_CLASS_L, 0, NULL, utf8proc_sequences + 8114, -1, 42787, -1, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_OTHER, 1},
   {UTF8PROC_CATEGORY_LL, 0, UTF8PROC_BIDI_CLASS_L, 0, NULL, NULL, 42786, -1, 42786, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_OTHER, 1},
   {UTF8PROC_CATEGORY_LU, 0, UTF8PROC_BIDI_CLASS_L, 0, NULL, utf8proc_sequences + 8116, -1, 42789, -1, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_OTHER, 1},
@@ -12490,8 +12487,6 @@
   {UTF8PROC_CATEGORY_MN, 0, UTF8PROC_BIDI_CLASS_NSM, 0, utf8proc_sequences + 11058, NULL, -1, -1, -1, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_EXTEND, 0},
   {UTF8PROC_CATEGORY_MN, 0, UTF8PROC_BIDI_CLASS_NSM, 0, NULL, NULL, -1, -1, -1, 25228, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_EXTEND, 0},
   {UTF8PROC_CATEGORY_MN, 0, UTF8PROC_BIDI_CLASS_NSM, 0, NULL, NULL, -1, -1, -1, 25296, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_EXTEND, 0},
-  {UTF8PROC_CATEGORY_MN, 7, UTF8PROC_BIDI_CLASS_NSM, 0, NULL, NULL, -1, -1, -1, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_OTHER, 0},
-  {UTF8PROC_CATEGORY_MN, 0, UTF8PROC_BIDI_CLASS_NSM, 0, NULL, NULL, -1, -1, -1, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_OTHER, 0},
   {UTF8PROC_CATEGORY_MC, 0, UTF8PROC_BIDI_CLASS_L, 0, NULL, NULL, -1, -1, -1, -1, 56, false, false, false, false, UTF8PROC_BOUNDCLASS_EXTEND, 0},
   {UTF8PROC_CATEGORY_MC, 0, UTF8PROC_BIDI_CLASS_L, 0, NULL, NULL, -1, -1, -1, 25364, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_SPACINGMARK, 0},
   {UTF8PROC_CATEGORY_MC, 0, UTF8PROC_BIDI_CLASS_L, 0, utf8proc_sequences + 11061, NULL, -1, -1, -1, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_SPACINGMARK, 0},
@@ -12509,7 +12504,6 @@
   {UTF8PROC_CATEGORY_MC, 0, UTF8PROC_BIDI_CLASS_L, 0, NULL, NULL, -1, -1, -1, 25568, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_SPACINGMARK, 0},
   {UTF8PROC_CATEGORY_MC, 0, UTF8PROC_BIDI_CLASS_L, 0, utf8proc_sequences + 11076, NULL, -1, -1, -1, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_SPACINGMARK, 0},
   {UTF8PROC_CATEGORY_MC, 0, UTF8PROC_BIDI_CLASS_L, 0, utf8proc_sequences + 11079, NULL, -1, -1, -1, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_SPACINGMARK, 0},
-  {UTF8PROC_CATEGORY_MN, 9, UTF8PROC_BIDI_CLASS_NSM, 0, NULL, NULL, -1, -1, -1, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_OTHER, 0},
   {UTF8PROC_CATEGORY_LU, 0, UTF8PROC_BIDI_CLASS_L, 0, NULL, utf8proc_sequences + 11082, -1, 71872, -1, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_OTHER, 1},
   {UTF8PROC_CATEGORY_LU, 0, UTF8PROC_BIDI_CLASS_L, 0, NULL, utf8proc_sequences + 11084, -1, 71873, -1, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_OTHER, 1},
   {UTF8PROC_CATEGORY_LU, 0, UTF8PROC_BIDI_CLASS_L, 0, NULL, utf8proc_sequences + 11086, -1, 71874, -1, -1, -1, false, false, false, false, UTF8PROC_BOUNDCLASS_OTHER, 1},
```

**Comment by stevengj** [comment]
I think the appveyor problem is unrelated, since I saw that with the previous commit.

**Comment by stevengj** [comment]
Let's try to get appveyor working again in a subsequent PR.

**Pull request merged**
