### PR TITLE
Update character widths from Unifont 8.0.01

### PR DESCRIPTION
**Pull request by jiahao**
Ref #50

### CODE REVIEW

**Comment by stevengj** [comment]
The Ruby oddness strikes again.  A difference in the `utf8proc_stage2table`, it seems like, but looking at the Ruby script I'm not sure why this would be non-deterministic.

@StefanKarpinski, you used to be a Ruby hacker, right?  Any idea why the data_generator.rb script would be non-deterministic?

**Comment by stevengj** [comment]
Note that e.g. u+06de now has a charwidth of 2 with this patch.  This seems odd to me: on my terminal, `۞` seems to have a charwidth of 1.

**Comment by jiahao** [comment]
Unifont 8.0.01 does define U+06DE to have fullwidth (1024 units); 7.0.06 gave it a negative RBearing of -1024 units so that it had width 0.

screen shot 2015-06-30 at 4 15 48 pm

**Comment by StefanKarpinski** [comment]
Hashes are unordered in Ruby 1.8.x (but not, I believe in 1.9.x). Perhaps that could affect things?

**Comment by stevengj** [comment]
@StefanKarpinski, I figured that the order of a hash would be undefined, but I'm not seeing where the script would depend on this.

**Comment by stevengj** [comment]
Has anyone been able to reproduce this failure locally?  I tried using the same Ruby version as on Travis (ruby 1.9.3p551, from #48), but it still passes.

**Comment by stevengj** [comment]
My inclination is to merge this and to open a separate issue for the data-generation Travis test, since that was a problem prior to this patch.

**Comment by ScottPJones** [comment]
How difficult is this Ruby code to understand?  We've got a much better language right here!

**Comment by stevengj** [comment]
I don't have the time to rewrite it from scratch right now, do you?

**Comment by ScottPJones** [comment]
It is really that complicated? I'm just asking, not trying to pressure you (or anybody) into rewriting it.
I was just wondering if the effort of finding that bug would be more than getting something in Julia that would save time in the future (and not require a person with Ruby expertise).

**Comment by StefanKarpinski** [comment]
The Ruby code is pretty straightforward, but it's also unclear why it would be nondeterministic. I don't think completely rewriting it is the answer.

**Comment by stevengj** [comment]
Merged since the Ruby problem on Travis is not a regression in this patch.

**Pull request merged**
