### PR TITLE
Fix MingW build test

### PR DESCRIPTION
**Pull request by petercolberg**
Fix MingW build test

### CODE REVIEW

**Comment by petercolberg** [comment]
Is it possible to lower the appveyer build timeout to say 5 minutes?

The current build hangs, and will only timeout after 30 or 40 minutes.

**Comment by aviks** [comment]
@petercolberg I've added the [WIP] tag to the title to indicate that this is experimental.  Please take it out once this PR is ready.

**Comment by tkelman** [comment]
The problem is that `cd /c/projects/utf8proc` is failing in msys, not the choice of generator. mingw make is a crippled version that is enough to build utf8proc but not much else.

**Comment by petercolberg** [comment]
When the line that creates /etc/fstab is removed, then `cd /c/projects/utf8proc` succeeds.

The build freezes as soon as `cmake … -G'MSYS Makefiles'` is executed.

**Comment by petercolberg** [comment]
I could finally trigger the following error message in the interactive session:
```
cc1.exe: The program can't start because libgmp-10.dll is missing from your computer.
Try reinstalling the program to fix this problem.
```
This is why cmake hangs when using the MSYS Makefiles generator.

**Comment by tkelman** [comment]
That sounds like a broken toolchain installation, cc @feodorfitsner. So changing the generator must be either changing which mingw compiler is getting run, or modifying the path so it's able to find libgmp.

**Comment by petercolberg** [comment]
It’s already fixed. Please merge after the Travis build succeeds.

**Comment by stevengj** [comment]
Looks great, thanks for following up on this!

**Pull request merged**
