### PR TITLE
use a different variable name for nested loop in bench.c

### PR DESCRIPTION
**Pull request by tkelman**
and declare it ahead of time to avoid "error: 'for' loop initial declarations are only allowed in C99 mode"

### CODE REVIEW

**Comment by tkelman** [comment]
Any objection @stevengj? Would you mind if I tagged 2.0.2 after this? The changes have been pretty negligible since 2.0.1 but it'd be useful for https://github.com/JuliaLang/julia/pull/17637

**Comment by stevengj** [comment]
Sure. File a PR that updates NEWS and the various version numbers before tagging.

**Comment by tkelman** [comment]
Right, I knew I was forgetting something.

**Comment by tkelman** [comment]
https://github.com/JuliaLang/utf8proc/pull/53 would probably also be able to address the build failure.

**Pull request merged**
